
import './styles/globals.css';
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/footer';

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'EPS Education',
  description: 'Generated by create next app',
  icons: {
    icon: [
      '/favicon.ico?v=4',
    ],
    apple: [
      '/apple-touch-icon.png?v=4',
    ],
    shortcut: [
      '/apple-touch-icon.png'
    ]
  },
  // manifest: '/site.webmanifest'
}
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}


